<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFEL9XPq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFEL9XPq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFEL9XPq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFEL9XPq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFEL9XPq\App_KernelDevDebugContainer([
    'container.build_hash' => 'FEL9XPq',
    'container.build_id' => '7fcf8475',
    'container.build_time' => 1649406425,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFEL9XPq');
